### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by kalletabur** [mrts/ask-jira#1]
Hi,

running ask-jira.py throw me AttributeError

```
(venv) user@deb82:~/ask-jira$ ./ask-jira.py projects
Traceback (most recent call last):
  File "./ask-jira.py", line 111, in <module>
    _main()
  File "./ask-jira.py", line 66, in _main
    argparser = _make_main_argument_parser()
  File "./ask-jira.py", line 78, in _make_main_argument_parser
    "commands:\n{0}".format(_list_local_commands()))
  File "./ask-jira.py", line 98, in _list_local_commands
    sorted_globals.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
```

Do you know how to fix this?

Kalle

**Comment by kalletabur** [comment]
System was using python3 instead of python2. Solved.

**Comment by mrts** [comment]
Thanks for the report! The script is now compatible with both Python 2 and 3.
